[tool.poetry]
name = "lambda-bedrock"
version = "0.1.0"
description = ""
authors = ["minhbear <minhbeardev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.129"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
