service: lambda-connect-bedrock

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  timeout: 60
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - "bedrock:InvokeModel"
          Resource: "*"
        - Effect: Allow
          Action:
            - "s3:GetObject"
          Resource: [
            "arn:aws:s3:::*"
          ]
        - Effect: Allow
          Action: [
                "transcribe:*"
          ]
          Resource: "*"

functions:
  connect_bedrock:
    handler: handler.handler